import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/context/CartContext";
import { AuthProvider } from "@/components/context/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TecnoShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-neutral"  data-theme="sunset" lang="en">
      <body  className={inter.className}>
        <AuthProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
